title: TumbleCraft
tagline: The home of TG and DBW
description: >- # this means to ignore newlines until "baseurl:"
  A New Minecraft Survival Server
base-url: ""
url: "http://github.tumblenet.ga/TumbleCraftJava/" # the base hostname & protocol for your site, e.g. http://example.com
repository: tumblenet/TumbleCraftJava

favicon: /images/logo.png
logo-url: /images/logo.png

excerpt_separator: <!--more-->

collections:
  posts:
    url: /news
  staff:
    output: true
    url: /staff
  servers:
    output: true
    url: /servers
  landmarks:
    output: true
    url: /landmarks
  playerbuilds:
    output: true
    url: /playerbuilds
  featured:
permalink: pretty
#permalink: /blog/:categories/:year/:month/:day/:title/
production: true


plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 #- jekyll-include-cache


# Build settings
markdown: kramdown
# theme: minima

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
  # Disable auto-generated ID's for headings
  auto_ids: true

excludes:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower.json
  - "*.sh"
  - README.md
  - gulffile.js
  - package.json
  - vendor
  - ".gitignore"
  - CNAME
  - icomoon-selection.json
